project:
  type: book
  output-dir: .

book:
  title: Anàlisi i Gestió de la Vegetació Dunar a la Costa Catalana
  date: June 15, 2024
  author:
    name: Victor Miguel Chura Quispe
  downloads: [pdf]
  chapters:
    - index.qmd
    - Chapters/Chapter1.qmd
    - Chapters/Chapter2.qmd
    - Chapters/Resum.qmd
    - Chapters/Introduccio.qmd
    - Chapters/Literatura.qmd
    - Chapters/Preliminars.qmd
    - Chapters/Metodologia.qmd
    - Chapters/Exploracio.qmd
    - Chapters/Divisio.qmd
    - Chapters/Contribucio.qmd
    - Chapters/Resultats.qmd
    - Chapters/Conclusions.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd

  site-url: https://nmfs-opensci.github.io/quarto-thesis/
  repo-url: https://github.com/nmfs-opensci/quarto-thesis
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor: 
    name: Dr. Ashok Kunil
    url: https://quarto.org/
  degree-name: Màster en Ciència de Dades Aplicada
  university: Universitat de Girona
  department: Departament d'Informàtica, Matemàtica Aplicada i Estadística
  group: Programa de Màster en Ciència de Dades Aplicada
  faculty: Escola Politècnica Superior
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
