project:
  type: book
  output-dir: .

book:
  title: Análisis de la Relación entre la Gestión de Playas, la Cobertura del Suelo y la Diversidad Vegetal en Dunas Costeras de Cataluña
  output-file: "tfm_victor_chura"
  date: May, 2025
  author:
    name: Victor Miguel Chura Quispe
  downloads: [pdf]
  chapters:
    - index.qmd
    - Chapters/01_Introduccio.qmd
    - Chapters/02_Literatura.qmd
    - Chapters/03_Preliminars.qmd
    - Chapters/04_Metodologia.qmd
    - Chapters/05_Contribucio.qmd
    - Chapters/06_Resultats.qmd
    - Chapters/07_Conclusions.qmd
    - references.qmd

  repo-url: https://github.com/nmfs-opensci/quarto-thesis
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor: 
    name: Dr. Javier Palarea Albaladejo
    url: https://www.udg.edu/ca/directori/pagina-personal?ID=180023
  degree-name: Máster en Ciencia de Datos
  university: Universitat de Girona
  faculty: Escola Politècnica Superior
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
lang: es

format:
  quarto-thesis-pdf: 
    classoption: ["11pt", "singlespacing", "headsepline"]
    documentclass: MastersDoctoralThesis
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
    lang: es
    include-in-header:
      - text: |
          % Spanish language configuration - let Quarto handle babel loading
          \AtBeginDocument{
            \addto\captionsspanish{
              \renewcommand{\contentsname}{Índice de contenidos}
              \renewcommand{\listfigurename}{Lista de figuras}
              \renewcommand{\listtablename}{Lista de tablas}
              \renewcommand{\figurename}{Figura}
              \renewcommand{\tablename}{Tabla}
              \renewcommand{\chaptername}{Capítulo}
              \renewcommand{\appendixname}{Apéndice}
              \renewcommand{\bibname}{Referencias}
              \renewcommand{\indexname}{Índice}
              \renewcommand{\abstractname}{Resumen}
              \renewcommand{\partname}{Parte}
              \renewcommand{\refname}{Referencias}
              \renewcommand{\proofname}{Demostración}
            }
            % Force Spanish language
            \def\tablename{Tabla}
            \def\figurename{Figura}
            \def\chaptername{Capítulo}
            \selectlanguage{spanish}
          }
