project:
  type: book
  output-dir: .

book:
  title: Análisis de la Relación entre la Gestión de Playas, la Cobertura del Suelo y la Diversidad Vegetal en Dunas Costeras de Cataluña
  output-file: "tfm_victor_chura"
  date: Julio 2025
  author:
    name: Victor Miguel Chura Quispe
  downloads: [pdf]
  chapters:
    - index.qmd
    - Chapters/01_Introduccio.qmd
    - Chapters/02_Literatura.qmd
    - Chapters/04_Metodologia.qmd
    - Chapters/05_Resultados.qmd
    - Chapters/06_Conclusions.qmd

  repo-url: https://github.com/vmchura/analysismanagementdunes
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor: 
    name: Dr. Javier Palarea Albaladejo
    url: https://www.udg.edu/ca/directori/pagina-personal?ID=180023
  degree-name: Máster en Ciencia de Datos
  university: Universitat de Girona
  faculty: Escola Politècnica Superior
  logo: images/logo.png
  logo-height: "2cm"

bibliography: [example.bib]
cite-method: biblatex
biblio-style: alphabetic
biblio-title: "Bibliografía"

execute:
  echo: false
  code-overflow: wrap

# Use lang to set main language
lang: es

format:
  quarto-thesis-pdf:
    classoption: ["11pt", "singlespacing", "headsepline"]
    documentclass: MastersDoctoralThesis
    urlcolor: blue              # External URLs (web links)
    linkcolor: blue             # Internal references (citations, cross-refs)
    citecolor: blue             # Bibliography citations specifically
    toclinkcolor: black         # Table of contents links
    toc-depth: 2
    # Load babel early with all required options before any other packages
    include-before-body:
      - text: |
          \selectlanguage{spanish}
    include-in-header:
      - text: |
          % Load babel with all required options at the very beginning
          \PassOptionsToPackage{spanish,bidi=default}{babel}
          % Spanish language customizations
          \AtBeginDocument{
            \addto\captionsspanish{
              \renewcommand{\contentsname}{Índice de contenidos}
              \renewcommand{\listfigurename}{Lista de figuras}
              \renewcommand{\listtablename}{Lista de tablas}
              \renewcommand{\figurename}{Figura}
              \renewcommand{\tablename}{Tabla}
              \renewcommand{\chaptername}{Capítulo}
              \renewcommand{\appendixname}{Apéndice}
              \renewcommand{\bibname}{Referencias}
              \renewcommand{\indexname}{Índice}
              \renewcommand{\abstractname}{Resumen}
              \renewcommand{\partname}{Parte}
              \renewcommand{\refname}{Referencias}
              \renewcommand{\proofname}{Demostración}
              \renewcommand{\supervisor}{Tutor}
            }
          }
          % Custom title page layout
          \makeatletter
          \renewcommand{\maketitle}{%
            \begin{titlepage}
              \newgeometry{margin=2.5cm}
              
              % University header with logo
              \begin{minipage}[t]{0.3\textwidth}
                \includegraphics[height=2cm]{images/logo.png}
              \end{minipage}%
              \begin{minipage}[t]{0.7\textwidth}
                \raggedright
                {\large\bfseries Universitat de Girona\\}
                {\large\bfseries Escola Politècnica Superior\\}
              \end{minipage}
              
              \vspace{2.5cm}
              
              % Title section
              \begin{center}
                {\huge\bfseries Trabajo Final de Máster}
              \end{center}
              
              \vspace{1.5cm}
              
              % Study program in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Estudio: Máster en Ciencia de Datos}
                \vspace{0.3cm}
              }}
              
              \vspace{0.8cm}
              
              % Title in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Título: \@title}
                \vspace{0.3cm}
              }}
              
              \vspace{0.8cm}
              
              % Document type in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Documento: Memoria}
                \vspace{0.3cm}
              }}
              
              \vspace{0.8cm}
              
              % Student info in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Alumno: \@author}
                \vspace{0.3cm}
              }}
              
              \vspace{0.8cm}
              
              % Supervisor and department info in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Tutor: Dr. Javier Palarea Albaladejo\\
                Departamento: Escola Politècnica Superior\\
                Área: Ciencia de Datos}
                \vspace{0.3cm}
              }}
              
              \vspace{0.8cm}
              
              % Date in box
              \noindent\fbox{\parbox{\textwidth}{%
                \vspace{0.3cm}
                {\large Convocatoria (mes/año): \@date}
                \vspace{0.3cm}
              }}
              
              \restoregeometry
            \end{titlepage}
            \cleardoublepage
          }
          \makeatother
          
          % Force title page to appear first
          \AtBeginDocument{\maketitle}